
INSERT INTO plm_properties(PROPERTYID,PROPERTY,VALUE,ENV,PROPCATEGORY,OVERRIDE,PRIORITY)VALUES(1,'log4j.rootLogger','ERROR, ROOT','DEV1','log4j','default',0);
INSERT INTO plm_properties(PROPERTYID,PROPERTY,VALUE,ENV,PROPCATEGORY,OVERRIDE,PRIORITY)VALUES(2,'maxThreads','101','DEV1','archive','default',0);